# Generated by Django 4.2 on 2025-06-10 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='StatusAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('category_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.categoryaction', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='Дата создания записи')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('category_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.categoryaction', verbose_name='Категория')),
                ('status_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.statusaction', verbose_name='Статус')),
                ('subcategory_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.subcategoryaction', verbose_name='Подкатегория')),
                ('type_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.typeaction', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='categoryaction',
            name='type_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.typeaction', verbose_name='Тип'),
        ),
    ]
