# Generated by Django 4.2 on 2025-06-11 07:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category_act',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='type_act', chained_model_field='type_act', null=True, on_delete=django.db.models.deletion.SET_NULL, sort=False, to='cashflow.categoryaction', verbose_name='Категория'),
        ),
    ]
