# Generated by Django 4.2 on 2025-06-11 08:41

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_transaction_category_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category_act',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='type_act', chained_model_field='type_act', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.categoryaction', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory_act',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category_act', chained_model_field='category_act', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.subcategoryaction', verbose_name='Подкатегория'),
        ),
    ]
