# Generated by Django 4.2 on 2025-06-13 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_transaction_category_act_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryaction',
            options={'verbose_name': 'Категория транзакций', 'verbose_name_plural': 'Категории транзакций'},
        ),
        migrations.AlterModelOptions(
            name='statusaction',
            options={'verbose_name': 'Статус транзакций', 'verbose_name_plural': 'Статусы транзакций'},
        ),
        migrations.AlterModelOptions(
            name='subcategoryaction',
            options={'verbose_name': 'Подкатегория транзакций', 'verbose_name_plural': 'Подкатегории транзакций'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='typeaction',
            options={'verbose_name': 'Тип транзакций', 'verbose_name_plural': 'Типы транзакций'},
        ),
        migrations.AlterField(
            model_name='categoryaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Категория с таким именем уже существует'}, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='statusaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Статус с таким именем уже существует'}, max_length=100, unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subcategoryaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Подкатегория с таким именем уже существует'}, max_length=100, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='typeaction',
            name='name',
            field=models.CharField(error_messages={'unique': 'Тип с таким именем уже существует'}, max_length=100, unique=True, verbose_name='Тип'),
        ),
    ]
